# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaliyCheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ipaddress', models.CharField(blank=True, max_length=45)),
                ('_hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('_ostype', models.CharField(blank=True, max_length=60, null=True)),
                ('_addtime', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
