# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaliyCheck', '0002_machine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_info',
            name='_addtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
