# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-27 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaliyCheck', '0004_lock_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='F5_PoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_poolMember_Img', models.CharField(blank=True, max_length=10, null=True)),
                ('_poolMember_name', models.CharField(blank=True, max_length=20, null=True)),
                ('_poolMember_status', models.CharField(blank=True, max_length=10, null=True)),
                ('_poolName', models.CharField(blank=True, max_length=50, null=True)),
                ('_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
