# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaliyCheck', '0005_f5_poolinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBMGuardium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_dbServer_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('_dbServertype', models.CharField(blank=True, max_length=20, null=True)),
                ('_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('_stap_status', models.CharField(blank=True, max_length=50, null=True)),
                ('_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
